# Generated by Django 3.0.8 on 2020-07-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logs',
        ),
        migrations.RenameField(
            model_name='regs',
            old_name='psw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='regs',
            old_name='uname',
            new_name='username',
        ),
    ]
