# Generated by Django 3.0.8 on 2020-07-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20200725_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male'), ('o', 'other')], max_length=2)),
                ('background', models.CharField(choices=[('s', 'science'), ('a', 'arts'), ('c', 'commerce'), ('o', 'other')], max_length=2)),
                ('occupation', models.CharField(choices=[('s', 'school'), ('c', 'college'), ('u', 'university'), ('t', 'teacher'), ('o', 'others')], max_length=2)),
                ('year', models.CharField(max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('picture', models.ImageField(max_length=50, upload_to='')),
                ('text', models.CharField(max_length=50)),
                ('achievements', models.FileField(max_length=50, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='regs',
        ),
    ]
