# Generated by Django 3.0.8 on 2020-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20200727_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.FileField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
