# Generated by Django 3.0.8 on 2020-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_auto_20200729_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.FileField(max_length=50, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(max_length=50, upload_to='image/'),
        ),
    ]
