# Generated by Django 3.0.8 on 2020-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_auto_20200729_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ques', models.TextField(max_length=500)),
                ('image', models.ImageField(max_length=50, upload_to='ques/')),
                ('files', models.FileField(max_length=50, upload_to='files/')),
            ],
        ),
    ]
