# Generated by Django 3.0.8 on 2020-08-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0014_auto_20200804_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
