# Generated by Django 3.0.8 on 2020-08-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0015_auto_20200804_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilee',
        ),
    ]
