# Generated by Django 3.0.8 on 2020-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0016_delete_profilee'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('picture', models.ImageField(max_length=50, upload_to='image/')),
                ('text', models.TextField(max_length=500)),
                ('achievements', models.FileField(max_length=50, upload_to='files/')),
            ],
        ),
    ]
