# Generated by Django 3.0.8 on 2020-08-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0017_profilee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profilee',
            new_name='profile',
        ),
    ]
