# Generated by Django 3.0.8 on 2020-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0019_auto_20200804_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='people',
            name='age',
        ),
        migrations.RemoveField(
            model_name='people',
            name='department',
        ),
        migrations.RemoveField(
            model_name='people',
            name='email',
        ),
        migrations.RemoveField(
            model_name='people',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='people',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='people',
            name='text',
        ),
        migrations.RemoveField(
            model_name='people',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='people',
            name='year',
        ),
        migrations.AddField(
            model_name='people',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
