# Generated by Django 3.0.8 on 2020-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ques', models.TextField(max_length=500)),
                ('image', models.ImageField(max_length=50, upload_to='ques/')),
                ('files', models.FileField(max_length=50, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('picture', models.ImageField(max_length=50, upload_to='image/')),
                ('text', models.TextField(max_length=500)),
                ('achievements', models.FileField(max_length=50, upload_to='files/')),
            ],
        ),
    ]
