# Generated by Django 3.0.8 on 2020-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ask',
        ),
        migrations.AddField(
            model_name='profile',
            name='files',
            field=models.FileField(default=1, max_length=50, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=0, max_length=50, upload_to='ques/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ques',
            field=models.TextField(default=3, max_length=500),
            preserve_default=False,
        ),
    ]
