# Generated by Django 3.0.8 on 2020-08-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_ask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='ask_id',
        ),
    ]
