# Generated by Django 3.0.8 on 2020-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200805_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
