# Generated by Django 3.0.8 on 2020-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_ask_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='pic',
            field=models.ImageField(max_length=50, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='files',
            field=models.FileField(max_length=50, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='image',
            field=models.ImageField(max_length=50, null=True, upload_to='ques/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='ques',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
