# Generated by Django 3.0.8 on 2020-08-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200806_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year',
            new_name='address',
        ),
    ]
