# Generated by Django 3.0.8 on 2020-08-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200806_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='files',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='ques/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='pic',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='ques',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workplace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
