# Generated by Django 3.0.8 on 2020-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20200807_0212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPerson',
        ),
        migrations.AddField(
            model_name='ask',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
