# Generated by Django 3.0.8 on 2020-08-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20200807_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='name',
        ),
    ]
