# Generated by Django 3.0.8 on 2020-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_ask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
