# Generated by Django 3.0.8 on 2020-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20200814_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='pic',
        ),
        migrations.AddField(
            model_name='ask',
            name='username',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
