# Generated by Django 3.0.8 on 2020-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20200814_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='files',
            field=models.FileField(blank=True, default=False, max_length=50, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='image',
            field=models.ImageField(blank=True, default=False, max_length=50, null=True, upload_to='ques/'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='ques',
            field=models.TextField(blank=True, default=False, max_length=500, null=True),
        ),
    ]
