# Generated by Django 3.0.8 on 2020-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20200814_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='files',
            field=models.FileField(blank=True, default=1, max_length=50, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ask',
            name='image',
            field=models.ImageField(blank=True, max_length=50, upload_to='ques/'),
        ),
    ]
