# Generated by Django 3.0.8 on 2020-08-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20200815_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='pic',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='ques/'),
        ),
    ]
