# Generated by Django 3.0.8 on 2020-08-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_user_extend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='pic',
        ),
        migrations.AddField(
            model_name='ask',
            name='email',
            field=models.EmailField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='user_extend',
        ),
    ]
